### ISSUE TITLE
DA v2 consensus error

### ISSUE THREAD

**Issue by Senna46** [sunriselayer/sunrise#119]
After upgrading to DA v2, there is a problem with a consensus error once sunrised is stopped.

```
10:28AM ERR CONSENSUS FAILURE!!! err="+2/3 committed an invalid block: wrong Block.Header.AppHash.  Expected E2160698E038B323AD4CCDD57D8D47D294D9CE21B4F4E152848A32B67F008514, got EFDAE576527D56E381BF1A4E0B3893A5EE52D94537C9A2CE2215D3ECCE515A77" module=consensus stack="goroutine 589 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x5e\ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine.func2()\n\t/home/user/go/pkg/mod/github.com/sunriselayer/sunrise-core@v0.0.5-cmt-v0.38.2/consensus/state.go:800 +0x46\npanic({0x3317360?, 0xc00ab1c8a0?})\n\t/usr/local/go/src/runtime/panic.go:770 +0x132\ngithub.com/cometbft/cometbft/consensus.(*State).finalizeCommit(0xc00133e708, 0x2e12a)\n\t/home/user/go/pkg/mod/github.com/sunriselayer/sunrise-core@v0.0.5-cmt-v0.38.2/consensus/state.go:1712 +0x1236\ngithub.com/cometbft/cometbft/consensus.(*State).tryFinalizeCommit(0xc00133e708, 0x2e12a)\n\t/home/user/go/pkg/mod/github.com/sunriselayer/sunrise-core@v0.0.5-cmt-v0.38.2/consensus/state.go:1681 +0x2e8\ngithub.com/cometbft/cometbft/consensus.(*State).handleCompleteProposal(0xc00133e708, 0x2e12a)\n\t/home/user/go/pkg/mod/github.com/sunriselayer/sunrise-core@v0.0.5-cmt-v0.38.2/consensus/state.go:2058 +0x372\ngithub.com/cometbft/cometbft/consensus.(*State).handleMsg(0xc00133e708, {{0x4982d40, 0xc00309c678}, {0xc00793a000, 0x28}})\n\t/home/user/go/pkg/mod/github.com/sunriselayer/sunrise-core@v0.0.5-cmt-v0.38.2/consensus/state.go:909 +0x178\ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine(0xc00133e708, 0x0)\n\t/home/user/go/pkg/mod/github.com/sunriselayer/sunrise-core@v0.0.5-cmt-v0.38.2/consensus/state.go:835 +0x3f1\ncreated by github.com/cometbft/cometbft/consensus.(*State).OnStart in goroutine 135\n\t/home/user/go/pkg/mod/github.com/sunriselayer/sunrise-core@v0.0.5-cmt-v0.38.2/consensus/state.go:397 +0x10c\n
```

This occurs regardless of the state; it does not occur until sunrised is stopped, but whenever it is stopped and resumed, the error occurs.

**Comment by Senna46** [comment]
Try this method
https://github.com/cosmos/cosmos-sdk/issues/20489
